#' @title Get all problems of a coco suite.
#'
#' @description
#' Iterates through all problems by calling \code{\link{cocoSuiteGetNextProblem}}.
#'
#' @template arg_suite
#' @return [\code{list} of \code{\link{CocoProblem}}]. Named with coco problem ids.
#' @export
cocoSuiteGetAllProblems = function(suite) {
  assertClass(suite, "CocoSuite")

  # We cannot do this while loop here, since the pointer generated by cocoSuiteGetNextProblem
  # will by overwritten on the next call!
  # while(!is.null(p <- cocoSuiteGetNextProblem(suite))) {
  #   problems[[p$id]] = p
  # }

  # Instead we need to iterate by hand and "skip" filtered problems
  n = cocoSuiteGetNumberOfProblems(suite)
  problems = list()
  for (i in seq_len(n)) {
    p = cocoSuiteGetProblem(suite, i - 1L) # problems start at index 0
    if (!is.null(p))
      problems[[p$id]] = p
  }
  addClasses(problems, "CocoProblemList")
}
